#!/usr/bin/env python3
"""Convert coastlines.js and borders.js to C++ header with static float arrays."""
import re, sys, os

def parse_js_segments(filepath):
    with open(filepath) as f:
        content = f.read()
    # Find all segment arrays: [[lon, lat], [lon, lat], ...]
    segments = []
    # Match inner arrays of [lon, lat] pairs
    for match in re.finditer(r'\[([^\[\]]*(?:\[[^\[\]]*\][^\[\]]*)*)\]', content):
        inner = match.group(1).strip()
        if not inner:
            continue
        # Check if this is a segment (contains [lon,lat] pairs) not a single pair
        pairs = re.findall(r'\[(-?[\d.]+),\s*(-?[\d.]+)\]', inner)
        if len(pairs) >= 2:
            segments.append([(float(lon), float(lat)) for lon, lat in pairs])
    return segments

def write_header(coast_segs, border_segs, outpath):
    with open(outpath, 'w') as f:
        f.write('// Auto-generated by tools/generate-geomdata.py — do not edit\n')
        f.write('// Source: Natural Earth 110m public domain data\n\n')
        f.write('#pragma once\n\n')
        f.write('namespace GeomData {\n\n')
        
        # Write coastlines
        all_coast = []
        coast_offsets = [0]
        for seg in coast_segs:
            for lon, lat in seg:
                all_coast.append(lon)
                all_coast.append(lat)
            coast_offsets.append(len(all_coast) // 2)
        
        f.write(f'// Coastlines: {len(coast_segs)} segments, {len(all_coast)//2} points\n')
        f.write(f'static const int COAST_SEGMENT_COUNT = {len(coast_segs)};\n')
        f.write(f'static const float COAST_DATA[] = {{\n')
        for i in range(0, len(all_coast), 10):
            chunk = all_coast[i:i+10]
            f.write('    ' + ', '.join(f'{v:.2f}' for v in chunk) + ',\n')
        f.write('};\n\n')
        
        f.write(f'static const int COAST_OFFSETS[] = {{\n    ')
        f.write(', '.join(str(o) for o in coast_offsets))
        f.write('\n};\n\n')
        
        # Write borders
        all_border = []
        border_offsets = [0]
        for seg in border_segs:
            for lon, lat in seg:
                all_border.append(lon)
                all_border.append(lat)
            border_offsets.append(len(all_border) // 2)
        
        f.write(f'// Borders: {len(border_segs)} segments, {len(all_border)//2} points\n')
        f.write(f'static const int BORDER_SEGMENT_COUNT = {len(border_segs)};\n')
        f.write(f'static const float BORDER_DATA[] = {{\n')
        for i in range(0, len(all_border), 10):
            chunk = all_border[i:i+10]
            f.write('    ' + ', '.join(f'{v:.2f}' for v in chunk) + ',\n')
        f.write('};\n\n')
        
        f.write(f'static const int BORDER_OFFSETS[] = {{\n    ')
        f.write(', '.join(str(o) for o in border_offsets))
        f.write('\n};\n\n')
        
        f.write('} // namespace GeomData\n')

if __name__ == '__main__':
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    coast = parse_js_segments(os.path.join(base, 'qml/js/coastlines.js'))
    border = parse_js_segments(os.path.join(base, 'qml/js/borders.js'))
    outpath = os.path.join(base, 'src/geomdata.h')
    write_header(coast, border, outpath)
    print(f'Generated {outpath}: {len(coast)} coast segments, {len(border)} border segments')