#!/usr/bin/env python3
"""Generate a compact timezone lookup grid for the Shadow Line app.

Produces qml/js/timezone_grid.js: a 0.5° resolution grid mapping every
(lat, lon) pair on Earth to a UTC offset and DST flag. The grid is
generated from the IANA timezone database via the timezonefinder library
(Python), which uses the timezone-boundary-builder polygon dataset
(https://github.com/evansiroky/timezone-boundary-builder).

Regeneration requirements:
    pip install timezonefinder   (pulls timezonefinder-data, numpy, h3)

The grid encodes each 0.5° cell as a single ASCII character. The encoding
is: char = chr(48 + offset_index * 2 + dst_flag), where offset_index maps
into the OFFSETS table (55 values from -12 to +14 in 0.5h increments)
and dst_flag is 1 if the timezone observes DST, 0 otherwise.

DST detection compares the UTC offset in January vs July for each IANA
timezone. If they differ by >= 0.5h, the timezone observes DST (dst_flag=1)
and the stored offset is the standard (winter) offset.

Resolution: 0.5° (361 lat steps x 721 lon steps = 260,281 cells)
Output size: ~313 KB
Generated data source: timezonefinder 9.x + timezonefinder-data 3.x
"""

import sys
import os

try:
    from timezonefinder import TimezoneFinder
    from zoneinfo import ZoneInfo
    from datetime import datetime, timezone
except ImportError:
    print("Error: timezonefinder not installed.", file=sys.stderr)
    print("  pip install timezonefinder", file=sys.stderr)
    sys.exit(1)

OFFSETS = [
    -12, -11.5, -11, -10.5, -10, -9.5, -9, -8.5, -8, -7.5,
    -7, -6.5, -6, -5.5, -5, -4.5, -4, -3.5, -3, -2.5,
    -2, -1.5, -1, -0.5, 0, 0.5, 1, 1.5, 2, 2.5,
    3, 3.5, 4, 4.5, 5, 5.5, 5.75, 6, 6.5, 7,
    7.5, 8, 8.5, 8.75, 9, 9.5, 10, 10.5, 11, 11.5,
    12, 12.75, 13, 13.75, 14,
]


# Encode into U+0100..U+016D to avoid null chars, backslashes, and quotes
# in the QML/JS string literal. charCodeAt() still works on BMP code points.
_GRID_BASE = 0x0100

def encode_cell(off, dst):
    best = min(range(len(OFFSETS)), key=lambda i: abs(OFFSETS[i] - off))
    return chr(_GRID_BASE + best * 2 + dst)


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(script_dir, "..", "qml", "js", "timezone_grid.js")

    tf = TimezoneFinder()
    tz_cache = {}

    def get_cell(lat, lon):
        tz_name = tf.timezone_at(lat=lat, lng=lon)
        if not tz_name:
            return encode_cell(round(lon / 15), 0)
        if tz_name in tz_cache:
            return tz_cache[tz_name]
        try:
            z = ZoneInfo(tz_name)
            now = datetime.now(timezone.utc)
            jan = now.replace(month=1, day=15, hour=12, minute=0, second=0).astimezone(z)
            jul = now.replace(month=7, day=15, hour=12, minute=0, second=0).astimezone(z)
            win_off = jan.utcoffset().total_seconds() / 3600
            jul_off = jul.utcoffset().total_seconds() / 3600
            has_dst = int(abs(win_off - jul_off) >= 0.5)
            std_off = min(win_off, jul_off) if has_dst else win_off
        except Exception:
            std_off = round(lon / 15)
            has_dst = 0
        c = encode_cell(std_off, has_dst)
        tz_cache[tz_name] = c
        return c

    # Generate: lat 90->-90, lon -180->180, step 0.5
    rows = []
    total = 0
    for lat_i in range(180, -181, -1):
        lat = lat_i / 2.0
        row = []
        for lon_i in range(-360, 361):
            lon = lon_i / 2.0
            row.append(get_cell(lat, lon))
            total += 1
        rows.append("".join(row))
        if (180 - lat_i) % 36 == 0:
            print(f"  lat={lat:>6.1f}  ({total:>7d} cells, {len(tz_cache)} tz cached)")

    grid = "".join(rows)
    print(f"Done: {total} cells, {len(tz_cache)} unique timezones")
    print(f"Grid size: {len(grid)} chars")

    with open(out_path, "w") as f:
        f.write(".pragma library\n")
        f.write(
            "// Timezone lookup grid -- maps (lat, lon) to UTC offset and DST flag.\n"
        )
        f.write("//\n")
        f.write(
            "// Generated by tools/generate_timezone_grid.py from the IANA timezone\n"
        )
        f.write(
            "// database via timezonefinder (uses timezone-boundary-builder polygons).\n"
        )
        f.write("// Regenerate with:  python3 tools/generate_timezone_grid.py\n")
        f.write("//\n")
        f.write(
            "// Resolution: 0.5 deg (361 lat x 721 lon = 260,281 cells)\n"
        )
        f.write(
            f"// Each cell is one Unicode char: chr({_GRID_BASE} + offset_index*2 + dst_flag)\n"
        )
        f.write(
            "// offset_index maps into OFFSETS (55 values from -12 to +14, step 0.5)\n"
        )
        f.write(
            "// dst_flag: 1 if DST is currently active at generation time, 0 otherwise\n"
        )
        f.write("var STEP = 0.5;\n")
        f.write("var LAT_MAX = 90;\n")
        f.write("var LON_MIN = -180;\n")
        f.write("var LON_COUNT = 721;\n")
        f.write(f"var OFFSETS = {OFFSETS!r};\n")
        f.write(f'var GRID = "{grid}";\n')
        f.write("function lookup(lat, lon) {\n")
        f.write("  var li = Math.round((LAT_MAX - lat) / STEP);\n")
        f.write("  var lo = Math.round((lon - LON_MIN) / STEP);\n")
        f.write("  if (li < 0) li = 0; if (li > 360) li = 360;\n")
        f.write("  if (lo < 0) lo = 0; if (lo > 720) lo = 720;\n")
        f.write(f"  var c = GRID.charCodeAt(li * LON_COUNT + lo) - {_GRID_BASE};\n")
        f.write("  var idx = Math.floor(c / 2);\n")
        f.write("  var dst = c % 2;\n")
        f.write("  return {o: OFFSETS[idx], d: dst};\n")
        f.write("}\n")

    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()